### ISSUE TITLE
False positive error when parsing string file

### ISSUE THREAD

**Issue by millerf** [CirkusApp/airstrings#4]
Creates a file with:
```
"TEST" = "- Visit https://anyurl.com/tutorials";
```

And it will fail to upload with this error:
```
Value in "TEST" = "- Visit https: is not a valid string or doesn’t have a terminating semicolon
```

**Comment by shpakovski** [comment]
Hey Fab, the string is treated as in C. So please try to escape it like this?

```
"key" = "value with https:\/\/domain.com":
```

**Comment by millerf** [comment]
Problem is that it keeps the `\/` it in the Gdocs...
I am not sure it is intended...

**Comment by shpakovski** [comment]
You’re right, this must be handled differently then. Thanks for checking, and sorry for inconvenience!

**Comment by shpakovski** [comment]
Hi Fab, it looks like this problem has been recently fixed by @CemerikikT Could you please verify and confirm?

**Comment by millerf** [comment]
I will have to recompile, then...

**Comment by shpakovski** [comment]
Correct, thanks in advance 👍

**Comment by millerf** [comment]
This is fixed. Thanks!
