### ISSUE TITLE
Error when running " swift package generate-xcodeproj --xcconfig-overrides AirSecrets.xcconfig"

### ISSUE THREAD

**Issue by millerf** [CirkusApp/airstrings#6]
I get `error: root manifest not found`

Fixed by running `swift package init --type executable` before running `swift package`. Maybe introduced by new Xcode.

It should be added to the `README.md`

**Comment by shpakovski** [comment]
Resolved, right?

**Comment by millerf** [comment]
Yes. Sorry.
